; Projeto de uma estação de telemetria utilizando LoRa e ESP32
; Trabalho para a matéria Redes de Computadores I do curso Engenharia Eletrônica e de Computação da UFRJ
;
; Aluno: Danilo Davi Gomes Fróes
; Professor: Luís Henrique Maciel Kosmalski Costa
; Turma: 2026.1

[platformio]
description = Projeto de uma estação de telemetria utilizando LoRa e ESP32

[env]
platform = espressif32 @^6.13.0
framework = espidf
monitor_speed = 115200
build_flags =
    -Wall            ; habilitando todos os avisos do compilador
    -Wextra          ; habilitando avisos extras
    -Werror          ; Transforma warnings em erros
    -std=c++23       ; usando o padrão C++23
    -Os              ; Otimização -Os com foco em reduzir o tamanho do código

[env:Transmissor]
board = esp32doit-devkit-v1
board_build.f_cpu = 240000000L
build_src_filter = +<*> -<src/Receptor>  ; Incluindo apenas os arquivos do transmissor
build_flags =
    ${env.build_flags}
    -D TRANSMISSOR   ; Definindo a macro para o transmissor

[env:Receptor]
board = esp32-c3-devkitm-1
board_build.f_cpu = 160000000L
build_src_filter = +<*> -<src/Transmissor>  ; Incluindo apenas os arquivos do receptor
build_flags =
    ${env.build_flags}
    -D RECEPTOR      ; Definindo a macro para o receptor